# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anteproyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('impacto_del_proyecto', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('importe', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='principal',
            field=models.ManyToManyField(related_name='PartidaP', to='anteproyecto.Partida'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='secundario',
            field=models.ManyToManyField(related_name='PartidaS', to='anteproyecto.Partida'),
        ),
    ]
