# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0003_auto_20160920_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='secundario',
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='impacto_del_proyecto',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='principal',
            field=models.ManyToManyField(to='anteproyecto.Partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partida',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partida',
            name='importe',
            field=models.FloatField(),
        ),
    ]
