# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0004_auto_20160921_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='secundario',
            field=models.ManyToManyField(related_name='PartidaS', to='anteproyecto.Partida'),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='principal',
            field=models.ManyToManyField(related_name='PartidaP', to='anteproyecto.Partida'),
        ),
    ]
